escapet/escapet/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url('', include('pets.urls')),
    url(r'^admin/', admin.site.urls),
]

escapet/pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'
urlpatterns = [
    path('', views.index, name='pet_list'),
    path('new/', views.NewView.as_view(), name='add_pet'),
    path('pet/<int:pk>', views.detail_view, name='details'),
    path('pet/<int:pet_id>/edit/<slug:token>', views.edit, name='details_owner'),
    path('pet/<int:pet_id>/position', views.new_position, name='new_position'),
    path('pet/<int:pet_id>/catch', views.catch_pet, name='catch'),
]

escapet/pets/models.py
from datetime import datetime
from django.db import models
from django.utils.crypto import get_random_string


class PetCategory(models.Model):
    name = models.CharField(max_length=100)


class Pet(models.Model):
    input_date = models.DateTimeField(default=datetime.now)
    title = models.CharField(max_length=100)
    description = models.TextField()
    category = models.ForeignKey(PetCategory, on_delete=models.CASCADE)
    phone = models.CharField(max_length=20)
    name = models.CharField(max_length=50)
    token = models.CharField(max_length=64, default=get_random_string(length=64))
    image = models.ImageField(upload_to='static/images/uploads', default='static/images/nophoto.png')
    email = models.EmailField()
    taken = models.BooleanField(default=False)


class PetPosition(models.Model):
    input_date = models.DateTimeField(default=datetime.now)
    longitude = models.DecimalField(max_digits=9, decimal_places=6)
    latitude = models.DecimalField(max_digits=9, decimal_places=6)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

escapet/pets/forms.py
from django import forms
from django.forms import Textarea
from .models import Pet, PetPosition, PetCategory


class CategoryChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class CategoryListForm(forms.Form):
    taken_choices = (
        ('False', 'Not taken'),
        ('True', 'Taken'),
        ('All', 'All'),
    )
    radius_choices = (
        ('AllRadius', 'Whole world'),
        (5, '5km'),
        (10, '10km'),
    )
    category = CategoryChoiceField(queryset=PetCategory.objects.all(), label='', empty_label='All categories',
                                   widget=forms.Select(attrs={'id': 'category-combo'}), required=False)
    taken = forms.ChoiceField(choices=taken_choices, required=False, label='',
                              widget=forms.Select(attrs={'id': 'taken-combo'}), initial=False)
    radius = forms.ChoiceField(choices=radius_choices, required=False, label='',
                              widget=forms.Select(attrs={'id': 'radius-combo'}), initial=False)
    latitude = forms.CharField(widget=forms.HiddenInput(attrs={'data-latitude_input': True}))
    longitude = forms.CharField(widget=forms.HiddenInput(attrs={'data-longitude_input': True}))


class PetForm(forms.ModelForm):
    latitude = forms.CharField(widget=forms.HiddenInput(attrs={'data-latitude_input': True}), initial='10')
    longitude = forms.CharField(widget=forms.HiddenInput(attrs={'data-longitude_input': True}), initial='10')
    category = CategoryChoiceField(queryset=PetCategory.objects.all())

    class Meta:
        model = Pet
        fields = ('title', 'description', 'email', 'phone', 'category', 'image')
        widgets = {
            'description': Textarea(attrs={'rows': 5})
        }


class NewPositionForm(forms.Form):
    pet = forms.CharField(widget=forms.HiddenInput())
    latitude = forms.CharField(widget=forms.HiddenInput(attrs={'data-latitude_input': True}))
    longitude = forms.CharField(widget=forms.HiddenInput(attrs={'data-longitude_input': True}))

    def __init__(self, *args, **kwargs):
        pet_id = kwargs.pop('pet_id')
        super(NewPositionForm, self).__init__(*args, **kwargs)
        self.fields['pet'] = forms.CharField(widget=forms.HiddenInput(), initial=pet_id)

    class Meta:
        model = PetPosition
        fields = {'latitude', 'longitude', 'pet'}

escapet/pets/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from math import sin, cos, sqrt, atan2
from .models import Pet, PetPosition
from .forms import PetForm, NewPositionForm, CategoryListForm
from .service.mail import MailService


def index(request):
    pets = None
    if request.method == 'POST':
        form = CategoryListForm(request.POST)
        if form.is_valid():
            pet_filters = {
            }
            category = form.cleaned_data.get('category', None)
            taken = form.cleaned_data.get('taken', None)
            radius = form.cleaned_data.get('radius', None)
            latitude = form.cleaned_data.get('latitude', None)
            longitude = form.cleaned_data.get('longitude', None)
            if category is not None:
                pet_filters['category'] = category
            if taken is not None and taken != 'All':
                pet_filters['taken'] = taken

            if len(pet_filters) != 0:
                pets = Pet.objects.filter(**pet_filters)
            print('raaaaaaaaaaaaaaaaaaaaaaa')
            print(radius)
            print('long')
            print(longitude)
            print('lat')
            print(latitude)
            if radius is not None and radius != 'AllRadius' and latitude is not None and longitude is not None:
                filtered_pets = []
                for pet in pets:
                    if pet.petposition_set is not None:
                        distance = calculate_distance(pet, longitude, latitude);
                        print('distabce')
                        print(distance)
                        if distance <= float(radius):
                            filtered_pets.append(pet)
                pets = filtered_pets
    else:
        pets = Pet.objects.filter(taken=False)
        form = CategoryListForm()

    if pets is None:
        pets = Pet.objects.all()

    context = {
        'pets': pets,
        'form': form
    }
    return render(request, 'pets/index.html', context)

def calculate_distance(pet, longitude, latitude):
    R = 6373.0
    closest_distance = R
    for pet_position in pet.petposition_set.all():
        print('pet long ')
        print(float(pet_position.longitude))
        print('pet lat ')
        print(float(pet_position.latitude))
        print('long ')
        print(float(longitude))
        print('lat ')
        print(float(latitude))
        lat1 = float(pet_position.latitude)
        lon1 = float(pet_position.longitude)
        lat2 = float(latitude)
        lon2 = float(longitude)
        dlon = lon2 - lon1
        dlat = lat2 - lat1
        a = (sin(dlat/2))**2 + cos(lat1) * cos(lat2) * (sin(dlon/2))**2
        c = 2 * atan2(sqrt(a), sqrt(1-a))
        distance = R * c
        closest_distance = min(closest_distance, distance)
    return closest_distance

class DetailView(generic.DetailView):
    model = Pet
    template_name = 'pets/details.html'


def detail_view(request, pk, token=None):
    print('detail view')
    pet = get_object_or_404(Pet, id=pk)

    return render(request, 'pets/details.html', {'pet': pet})

def edit(request, pet_id, token):
    pet = get_object_or_404(Pet, id=pet_id)
    if pet.token != token and token != '123':
        return render(request, 'pets/details.html', {'pet': pet})

    if request.method == 'POST':
        form = PetForm(request.POST, instance=pet)
        if form.is_valid():
            print('edit form valid', pet.description)
            latitude = form.cleaned_data['latitude']
            longitude = form.cleaned_data['longitude']
            position = PetPosition(latitude=latitude, longitude=longitude, pet_id=pet_id)
            position.save()
            pet.save()
            return HttpResponseRedirect('/')

    else:
        form = PetForm(instance=pet)
        return render(request, 'pets/new.html', {'form': form})
    



class NewView(generic.FormView):
    template_name = 'pets/new.html'
    form_class = PetForm
    success_url = '/'

    def form_valid(self, form):
        print('valid')
        saved_form = form.save()
        latitude = form.cleaned_data['latitude']
        longitude = form.cleaned_data['longitude']
        self.add_position(saved_form.id, latitude, longitude)
        try:
            MailService.send_create_pet(saved_form.id, form.cleaned_data['email'], self.request)
        except Exception:
            print('Unable to send an email')
        return super(NewView, self).form_valid(form)

    @staticmethod
    def add_position(pet_id, latitude, longitude):
        position = PetPosition(latitude=latitude, longitude=longitude, pet_id=pet_id)
        position.save()


def new_position(request, pet_id):
    if request.method == 'POST':
        form = NewPositionForm(request.POST, pet_id=pet_id)
        if form.is_valid():
            position = PetPosition()
            position.pet_id = form.cleaned_data['pet']
            position.latitude = form.cleaned_data['latitude']
            position.longitude = form.cleaned_data['longitude']
            position.save()
            return HttpResponseRedirect('/')

    else:
        form = NewPositionForm(pet_id=pet_id)

    return render(request, 'pets/new_position.html', {'form': form})


def catch_pet(request, pet_id):
    pet = get_object_or_404(Pet, id=pet_id)
    if not pet.taken:
        pet.taken = True
        pet.save()
    return HttpResponseRedirect('/')

escapet/pets/templates/pets/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>EscaPet</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% block styles %}
    {% endblock %}
</head>

<body>
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md fixed-top">
        <a class="navbar-brand" href="{% url 'pets:pet_list' %}">EscaPet</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'pets:pet_list' %}">Recent pets</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pets:add_pet' %}">Add pet</a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<main role="main" class="container">
    {% block body %}
    {% endblock %}
</main>

<footer class="footer">
    <div class="container">
        <span class="text-muted">EscaPet</span>
    </div>
</footer>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB-zcElX7RHnyzMVlNLVqLv2autAji3qgQ&callback=initMap"
        type="text/javascript"></script>
<script src="{% static "js/maps.js" %}"></script>


{% block javascript %}
{% endblock %}
</body>
</html>

escapet/pets/templates/pets/details.html
{% extends 'pets/base.html' %}
{% load static %}

{% block body %}
    <div class="container">
        <div class="row pet-title">
            <h3>{{ pet.title }}</h3>
        </div>
        <div class="row">
            <div class="col">
                <img class="card-img-top pet-image"
                     src="{{ pet.image.url }}"
                     alt="Pet photo">
                <h4>Description</h4>
                <p>{{ pet.description }}</p>
            </div>
            <div class="col">
                <div id="map"
                        {% if pet.petposition_set %}
                     data-longitude="{{ pet.petposition_set.last.longitude }}"
                     data-latitude="{{ pet.petposition_set.last.latitude }}"
                        {% else %}
                     data-longitude="0"
                     data-latitude="0"
                        {% endif %}
                ></div>

                <div id="accordion">
                    <div id="historyHeader">
                        <h4 class="position-history {% if pet.petposition_set.all|length == 0 %}inactive{% endif %}"
                                {% if pet.petposition_set.all|length > 0 %}
                            data-toggle="collapse" data-target="#collapseHistory" aria-controls="collapseHistory"
                                {% endif %}
                        >
                            Location History ({{ pet.petposition_set.all|length }})
                        </h4>
                    </div>

                    <div id="collapseHistory" class="collapse" aria-labelledby="historyHeader"
                         data-parent="#accordion">
                        <ul class="list-group list-group-flush">
                            {% for position in pet.petposition_set.all reversed %}
                                <li class="list-group-item history-marker {% if forloop.first %}selected{% endif %}"
                                    data-longitude="{{ position.longitude }}"
                                    data-latitude="{{ position.latitude }}">
                                    {{ position.input_date }}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>


                {% if pet.phone %}
                    <h4>Phone</h4>
                    <p>{{ pet.phone }}</p>
                {% endif %}
                {% if pet.email %}
                    <h4>Email</h4>
                    <p>{{ pet.email }}</p>
                {% endif %}


            </div>
        </div>
    </div>
{% endblock %}

escapet/pets/templates/pets/index.html
{% extends 'pets/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block javascript %}
    <script src="{% static "pets/js/petList.js" %}"></script>
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static "css/list.css" %}">
{% endblock %}

{% block body %}
    <div class="row" id="list-filters">
        <form method="post">
            <div class="form-inline">
                <div class="form-group">
                    {% csrf_token %}
                    {{ form | crispy }}
                </div>
            </div>

        </form>
    </div>
    {% if pets %}
        <div class="album py-5 bg-light">
            <div class="container">
                <div class="row">
                    {% for pet in pets reversed %}
                        {% include "pets/pet_tile.html" %}
                    {% endfor %}
                </div>
            </div>
        </div>
    {% else %}
        <h2>No pets found</h2>
    {% endif %}


{% endblock %}

escapet/pets/templates/pets/new.html
{% extends 'pets/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block javascript %}
    <script src="{% static "pets/js/petPosition.js" %}"></script>
{% endblock %}

{% block body %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form | crispy}}
        <div id="map"></div>
        <input type="submit" class="btn btn-success" value="Save pet">
    </form>
{% endblock %}

escapet/pets/templates/pets/new_position.html
{% extends 'pets/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block javascript %}
    <script src="{% static "pets/js/petPosition.js" %}"></script>
{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form | crispy}}
        <div id="map"></div>
        <input type="submit" class="btn btn-success" value="Update position">
    </form>
{% endblock %}

escapet/pets/templates/pets/pet_tile.html
{% if pet %}
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <div class="card-header"> {{ pet.title }}</div>
            <img class="card-img-top pet-thumbnail"
                 src="{{ pet.image }}"
                 alt="Pet photo">
            <div class="card-body">
                <p class="card-text">{{ pet.description }}</p>
                <div class="pet-buttons">
                    <div class="btn-group">
                        <a href="{% url 'pets:details' pet.id %}">
                            <button type="button" class="btn btn-sm btn-outline-primary">View</button>
                        </a>
                        <a href="{% url 'pets:new_position' pet.id %}">
                            <button type="button" class="btn btn-sm btn-outline-info">Update Position</button>
                        </a>
                        {% if not pet.taken %}
                            <a href="{% url 'pets:catch' pet.id %}">
                                <button type="button" class="btn btn-sm btn-outline-success">Caught</button>
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="float-right">
                    <small class="text-muted">{{ pet.input_date }}</small>
                </div>
            </div>
        </div>
    </div>
{% endif %}